### ISSUE TITLE
Typo in README.md and Julia Version

### ISSUE THREAD

**Issue by chloemadeleine** [rohitsupekar/learning-active-matter-equations#1]
In section **2. Spectral Representation [Julia]** of README.md, I believe it should say "Run `save_representation.jl`." rather than "Run ." 

Also it didn't like Julia 1.9 so I switched to 1.7 and it worked fine after that.

**Comment by rohitsupekar** [comment]
Thanks a lot, much appreciated! I updated the the readme to address both the issues you pointed through the following commits

1625562414d8dae35e4e6d15239d8a68219f179c
19374d2b560a35421c297e3b78e0f99fa1d2d148

**Comment by rohitsupekar** [comment]
Closing since this has been addressed
